### ISSUE TITLE
MemeDataService to Retrieve Data About Memes

### ISSUE THREAD

**Issue by Step7750** [MemePlace/Frontend#11]
The meme data service should allow the retrieval of meme data from the API server given its unique ID.

**Comment by xiningchen** [comment]
Um, I would like some clarification for this issue... Can someone take a look at the meme_service branch?

**Comment by Step7750** [comment]
Here's my current progress on the generic API service: https://github.com/SENG513/Frontend/tree/feature/api-data-service/src/app/api

**Comment by Step7750** [comment]
Unblocked by #23

**Comment by xiningchen** [comment]
So what is meme service suppose to do? It doesn't quite make sense to me that we retrieve meme's using a unique id... How are we going to know what ID we'll get?

**Comment by Step7750** [comment]
So the main calls to the API at first would just be fetching the top X memes which would returns their ID as well. So if someone clicks on one of the memes, we'd use that ID we have to fetch further details.

The meme service handles everything in relation to fetching data for/about memes. It should be able to return the top memes, details about a meme, and memes for a community paginated etc...

It may be easier to think about what is required by having the meme backend solidified.

**Comment by xiningchen** [comment]
Can I help do the meme backend? I think if I work a bit on that, things will clear up for me... and I want to know what's even going on in the backend. lol

**Comment by Step7750** [comment]
Sure!

**Comment by Step7750** [comment]
Closed in https://github.com/MemePlace/Frontend/pull/58
