### ISSUE TITLE
Auto card sizing algorithm

### ISSUE THREAD

**Issue by xiningchen** [MemePlace/Frontend#16]
Takes the memes that needs to be loaded and determine optimal height and width so that card placement fits the page width. In meme browsing mode, it should be height-fixed, while width can change.

**Comment by bandgeekdante** [comment]
Should this use the same branch as meme_cards? (or a branch off of that branch)

**Comment by Step7750** [comment]
If @xiningchen is working on the actual cards, then you probably don't want to work on the same branch as her. You may want to wait until her branch is partially finished and/or merged before branching off of it.

**Comment by Step7750** [comment]
https://github.com/SENG513/Frontend/pull/17 fixes this for height-fixed.

I think the only case remaining is width-fixed on mobile to encompass the full screen width.

**Comment by bandgeekdante** [comment]
I will implement the fixed width for mobile.

**Comment by bandgeekdante** [comment]
@xiningchen @Step7750 Where does height-fixing happen in the code? I tested this by adding an image and the height wasn't fixed
