### ISSUE TITLE
Meme Layout Algorithm

### ISSUE THREAD

**Issue by Step7750** [MemePlace/Frontend#30]
Currently, the layout just fixes memes by a given height and fills them onto the page.

This can cause issues such as in 
![image](https://user-images.githubusercontent.com/11811793/38276018-fe58c922-3750-11e8-8a37-ec12d41a4e1b.png)

where there are gaps at the end of the row that don't fit the next meme.

Since the order that the images appear in is important, we can't use a partition algorithm that may present confusing and differing results to the user.

There are a couple approaches that can be taken to reduce this by effectively scaling the height of each row based upon the contents to ensure it fits perfectly.

We can solve for the height of a row if we know the total width. In order to know how many images we should put on a given row, we can add images until the row goes below a given threshold height.

You can find more details here: http://blog.vjeux.com/2012/image/image-layout-algorithm-google-plus.html

Continuing article: http://blog.vjeux.com/2014/image/google-plus-layout-find-best-breaks.html

**Comment by Step7750** [comment]
Some progress on this issue on the `feature/browse-layout-algo` branch:
![image](https://user-images.githubusercontent.com/11811793/38401920-d9c47cc0-3915-11e8-9150-6e4e4695cd2c.png)

**Comment by Step7750** [comment]
Yeah, it's hard to get the far right stuff to align due to differing widths beyond my control.

**Comment by xiningchen** [comment]
I think it's good enough~ :P

**Comment by bandgeekdante** [comment]
Is this feature good to go?

**Comment by Step7750** [comment]
No, it needs tweaking. It probably won't be done by tomorrow.

**Comment by Step7750** [comment]
Closed in #87
