### ISSUE TITLE
Interactive Meme Dialog

### ISSUE THREAD

**Issue by Step7750** [MemePlace/Frontend#5]
Triggering this dialog will open up an enlarged version of the meme card along with further details about the meme and the comments on it.

**Comment by bandgeekdante** [comment]
So I've been trying to make "MemeCard" into its own module, with the regular card and the dialog and components inside the module. However, I've just been running into a ton of issues doing it this way. Should I just make a new separate component for the meme dialog?

**Comment by xiningchen** [comment]
I think it should be it's own component.

**Comment by bandgeekdante** [comment]
Closed via #57
