### ISSUE TITLE
Login/Register Dialogs Styling

### ISSUE THREAD

**Issue by Step7750** [MemePlace/Frontend#50]
* The login and register dialogs should be a bit more wide and the same width
* The register dialog should have a custom validator for the username to check if it is available (Similar to https://github.com/MemePlace/Frontend/pull/44/files#diff-c355330e18a492e282503231b5990217R32)

**Comment by Step7750** [comment]
@Niustein Any updates on this issue?

**Comment by Niustein** [comment]
I think I'm pretty close to being done. The login/dialog styling was done but I ran into the issue with the slack issue in UserService which is making the username check impossible to check. I tried debugging the error to no avail.

"loggedIn$ = this.loggedInSource.distinctUntilChanged().asObservable();" with error:
"Error in src/app/api/user.service.ts<18,58>: error TS 2339: Property 'asObservable' does not exist on type 'Observable<boolean>'.

**Comment by Niustein** [comment]
Saw the fix to the isObservable, still running into an error with my branch for some reason (despite nothing really changing)...

I created a new branch and pulled from master and login/reg worked again, so I'm going to go through the code I added and figure out where the error is coming from. Will have this done in a few hours.
