### ISSUE TITLE
Sidebar Interaction Fixes

### ISSUE THREAD

**Issue by Step7750** [MemePlace/Frontend#52]
The side bar should remember if the user forcefully closed it or not and not reopen unless they explicitly open it again. By default the side bar should be open on desktop unless they close it.

**Comment by Dave0921** [comment]
For this feature, should the side bar remember if it's closed or not based on the user logged in, or should it be based on session (sidebar will reset if the browser is closed)?

**Comment by Step7750** [comment]
I think it should remember across browser startups. You could use the StorageService in https://github.com/MemePlace/Frontend/pull/46.

**Comment by Step7750** [comment]
I'd recommend making a service such as `SidebarService` for this and let it store whether the sidebar is currently open, have an emitter to allow other components to subscribe to changes, and it can handle storing whether the bar should be open.

**Comment by Dave0921** [comment]
I have the sidebar remembering whether it was opened/closed using emitters, however, I'm not sure on how to use Observables to subscribe to changes.
