### ISSUE TITLE
Sign In/Sign up Dialogs

### ISSUE THREAD

**Issue by Step7750** [MemePlace/Frontend#6]
There should be two separate dialog components that present the user with either logging in or signing up with a form-like interface.

**Comment by Step7750** [comment]
You are no longer blocked once https://github.com/SENG513/Server/pull/15 merges in

**Comment by Niustein** [comment]
Based on our conversation in class today (and from https://github.com/SENG513/Frontend/pull/23). Should we make e-mail optional or exclude it entirely?

**Comment by Step7750** [comment]
It is optional now https://github.com/SENG513/Server/issues/18
