### ISSUE TITLE
Bug in user service causing compilation errors

### ISSUE THREAD

**Issue by bandgeekdante** [MemePlace/Frontend#69]
Line 18 of user.service.ts is currently as follows:
loggedIn$ = this.loggedInSource.distinctUntilChanged().asObservable();
This generates the error
ERROR in src/app/api/user.service.ts(18,58): error TS2339: Property 'asObservable' does not exist on type 'Observable<boolean>'.
This sometimes (but not always) blocks compilation of the whole app.

**Comment by Dave0921** [comment]
Managed to fix this by switching the distinctUntilChanged() and asObservable() like so:

`loggedIn$ = this.loggedInSource.asObservable().distinctUntilChanged;`

I can login now, but it messses with some of the code in meme-card.component.ts
