### ISSUE TITLE
Navigation Sidebar

### ISSUE THREAD

**Issue by Step7750** [MemePlace/Frontend#9]
Allows the user to easily click communities that they have favourited with a possible interface for allowing them to see the Top X communities or maybe ones that may be relevant to them.

**Comment by Step7750** [comment]
This should probably also provide a button to create new communities

**Comment by ClaytonVis** [comment]
Perhaps toggle the sidebar when a button is clicked. It's pretty clunky on mobile otherwise.

**Comment by Dave0921** [comment]
Yup. Thankfully, Angular Material already provides the toggle sidebar functionality for mobile/ when the screen gets resized to a smaller width.

**Comment by Dave0921** [comment]
If a user creates a community, do they become the "moderator" of the community (ex. they can change the name of the community, delete community, etc.)?

**Comment by Step7750** [comment]
They'd be the "owner" which would have privileges above moderators if we implemented that. We currently don't have an interface planned for managing your created communities.

**Comment by Dave0921** [comment]
Oh okay. 
I've setup the sidebar to allow users to favourite communities, and display favourited communities before the top communities. How would we determine which communities are considered the "top" communities?

**Comment by Step7750** [comment]
Sort by most favourited?

**Comment by Dave0921** [comment]
I created a list of favourited communities, above the list of top communities. There is a strange bug where if I want to unfavourite one of the favourited communities from the favourited communities list, it removes the favourited community from list of favourites (which is good), but also refreshes the page... not sure why the refreshing happens.

**Comment by Step7750** [comment]
I replied to your PR with a fix that should resolve the issue. Let me know if it doesn't.

**Comment by Dave0921** [comment]
Yup, I made the changes and it works now; thanks!

**Comment by Dave0921** [comment]
Also, I wanted to give users a convenient way of managing their favourited communities from the navigation sidebar, so that they can easily favourite/unfavourite communities. We can remove this option if it doesn't have much use, since I know we are also implementing a favourite button on each individual community page.

**Comment by Step7750** [comment]
When you retrieve the memes from the community service, it is sorted before it is sent to you (https://github.com/MemePlace/Frontend/blob/master/src/app/api/community.service.ts#L38).

**Comment by Step7750** [comment]
Closed in https://github.com/MemePlace/Frontend/pull/26
